### ISSUE TITLE
Problem with library llibtbb.dylib for mac Users

### ISSUE THREAD

**Issue by brunnoattorre** [mrnugget/opencv-haar-classifier-training#10]
Based on: http://stackoverflow.com/questions/23363678/ld-library-not-found-for-llibtbb-dylib
Due to a misspell in the opencv.pc, this library is misspelled into the config file of Mac users. Due to that, we get a when running the g++ command:
ld: library not found for -libtbb.dylib

To fix this, it's required to correct the opencv.pc, by putting the correct path of the library. For instance: 
/usr/local/lib/libtbb.dylib.

If needed, I can open a PR for this to put into the instruction part.

**Comment by mrnugget** [comment]
Isn't that fixed by using sed (as described in the README here) like so?

```
g++ `pkg-config --libs --cflags opencv | sed 's/libtbb\.dylib/tbb/'`
```

The second answer in the SO thread you linked to mentions this :)
