### ISSUE TITLE
Image reader can not be created from -vec samples.vec and -bg negatives.txt.

### ISSUE THREAD

**Issue by bogong17** [mrnugget/opencv-haar-classifier-training#11]
When I was doing the step 8, it showed:
Image reader can not be created from -vec samples.vec and -bg negatives.txt.
Do you have any idea why i got this error?

Thanks

**Comment by mrnugget** [comment]
No, sorry. That's not nearly enough information.

Which version of OpenCV are you using? On which operating system? Which commands did you run successfully? Which ones failed? What's the output of these commands?

**Comment by phillchill** [comment]
For posterity: In my experience this error appears when you are specifying a non existing vec or bg file to `opencv-traincascade`. Check whether you're referring to your .vec and negatives.txt files correctly (or that they exist in the first place).

**Comment by mrnugget** [comment]
Thanks for chiming in @phillchill. 

Since it's been nearly 2 months an no reply with more information by @bogong17 I'm closing this for now.

**Comment by ztwj** [comment]
-vec samples.vec and -bg negatives.txt use obslute path
