### ISSUE TITLE
would this work with opencv 3.1

### ISSUE THREAD

**Issue by arpit1997** [mrnugget/opencv-haar-classifier-training#12]
hi I am using opencv3.1-dev. I can not find the folder haartraining under ~opencv/apps/ directory. I searched required files in opencv github repository but i could not find it
`unnirajendran-SVF15318SNW% cd opencv/apps `
`unnirajendran-SVF15318SNW% ls`
`annotation	createsamples		 traincascade
CMakeLists.txt	interactive-calibration`
`unnirajendran-SVF15318SNW% ls -l`
`total 20
drwxrwxr-x 2 unnirajendran unnirajendran 4096 May  6 14:47 annotation
-rw-rw-r-- 1 unnirajendran unnirajendran  209 May  6 14:47 CMakeLists.txt
drwxrwxr-x 3 unnirajendran unnirajendran 4096 May 15 13:32 createsamples
drwxrwxr-x 2 unnirajendran unnirajendran 4096 May  6 14:47 interactive-calibration
drwxrwxr-x 2 unnirajendran unnirajendran 4096 May 15 13:41 traincascade`
`unnirajendran-SVF15318SNW% `

**Comment by mrnugget** [comment]
Looks like it doesn't. I don't have the time nor the energy to update the guide for OpenCV 3.x. It works as described with 2.4.x. Feel free to send a pull request if you get it working.
