### ISSUE TITLE
struct.error: unpack requires a string argument of length 12

### ISSUE THREAD

**Issue by xjdeng** [mrnugget/opencv-haar-classifier-training#14]
If you get the following error:

```
Traceback (most recent call last):
  File "opencv-haar-classifier-training/tools/mergevec.py", line 171, in <module>
    merge_vec_files(vec_directory, output_filename)
  File "opencv-haar-classifier-training/tools/mergevec.py", line 134, in merge_vec_files
    val = struct.unpack('<iihh', content[:12])
struct.error: unpack requires a string argument of length 12
```

then try deleting all vector files of size 0 from your input directory before running it again!

**Comment by mrnugget** [comment]
Thanks for the hint! Would you open a pull request that adds this to the README?

**Comment by mrnugget** [comment]
Documented in #15 .

**Comment by ardaunal4** [comment]
Hi.I have this problem but, I am sorry to say, I don't know how can I find which vectors have 0 size.Can you help me about this problem?
