### ISSUE TITLE
Compiling mergevec.cpp failing on OSX 10.9

### ISSUE THREAD

**Issue by moezzie** [mrnugget/opencv-haar-classifier-training#2]
The compiling of mergevec.cpp fails on OSX 10.9 with the following errors
Command:
`g++ `pkg-config --libs --cflags opencv` -I. -o mergevec mergevec.cpp\
  cvboost.cpp cvcommon.cpp cvsamples.cpp cvhaarclassifier.cpp\
  cvhaartraining.cpp\
  -lopencv_core -lopencv_calib3d -lopencv_imgproc -lopencv_highgui -lopencv_objdetect`

Error:
`ld: library not found for -llibtbb.dylib
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Since I do want to run opencv with tbb my solution was simply to
1. Go through steps 1 - 5 in the read me (create samples)
2. Uninstall opencv (brew uninstall opencv)
3. Install opencv without tab (brew install opencv)
4. Compile mergevec.cpp 
5. Uninstall opencv (brew uninstall opencv)
6. Install opencv with tbb (brew install --with-tbb opencv)

This works fine, but is subpotimal.
I couldn’t for the life of me get the compiler to link libtbb. Not sure whats wrong.
Can I help with providing information of any sort?

**Comment by Glavin001** [comment]
This resolved the `ld: library not found for -llibtbb.dylib` issue for me: http://stackoverflow.com/a/23582975/2578205 

>Suppose libtbb.dylib is in /usr/local/lib/libtbb.dylib and opencv.pc is in /usr/local/lib/pkgconfig (The location may vary depending on where you install tbb and pkg-config)
>
>Then edit /usr/local/lib/pkgconfig/opencv.pc, change -llibtbb.dylib to /usr/local/lib/libtbb.dylib

**Comment by jacksonkr** [comment]
@Glavin001 For whatever reason, your solution isn't working for me.

**Error**
```
[ 16%] Built target compressed_depth_image_transport_gencfg
[ 33%] Linking CXX shared library /Users/Jackson/ros_catkin_ws/devel_isolated/compressed_depth_image_transport/lib/libcompressed_depth_image_transport.dylib
ld: library not found for -ltbb
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/Jackson/ros_catkin_ws/devel_isolated/compressed_depth_image_transport/lib/libcompressed_depth_image_transport.dylib] Error 1
make[1]: *** [CMakeFiles/compressed_depth_image_transport.dir/all] Error 2
make: *** [all] Error 2
```

**Modified /usr/local/lib/pkgconfig/opencv.pc**
```
# Package Information for pkg-config

prefix=/usr/local/Cellar/opencv/2.4.12_2
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir_old=${prefix}/include/opencv
includedir_new=${prefix}/include

Name: OpenCV
Description: Open Source Computer Vision Library
Version: 2.4.12
Libs: -L${exec_prefix}/lib -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab /usr/local/lib/libtbb.dylib
Cflags: -I${includedir_old} -I${includedir_new}
```

Am I missing something?
