### ISSUE TITLE
I got multiple object detections without actual image detection.

### ISSUE THREAD

**Issue by datomnurdin** [mrnugget/opencv-haar-classifier-training#21]
I'm ran this script but I got multiple object detections without actual image detection.

```
chmod +x build_all.sh
./build_all.sh
./facedetect --scale=2 --cascade="/Users/ZERO/RM1/classifier/cascade.xml"
```

![screenshot 2016-09-05 13 12 18](https://cloud.githubusercontent.com/assets/5416242/18237918/ccd731ec-7369-11e6-8a02-520094e1a2ec.png)

I got 51 positive images and 632 negative images. I ran this command to train the model (only 10 stages).

```
opencv_traincascade -data /Users/ZERO/RM1/classifier -vec /Users/ZERO/RM1/samples.vec -bg /Users/ZERO/Dropbox/RM1/negative_images/negatives.txt -numStages 10 -minHitRate 0.999 -maxFalseAlarmRate 0.5 -numPos 1000 -numNeg 600 -w 80 -h 40 -mode ALL -precalcValBufSize 1024 -precalcIdxBufSize 1024
```

Please advice. Thank you.

**Comment by mrnugget** [comment]
That seems like the data used for training wasn't good enough. I ran into the same issue once. Increasing the number of samples (both positive and negative) did the trick -- with the quality of the samples staying the same.
