### ISSUE TITLE
mergevec.py for Python 3.x

### ISSUE THREAD

**Issue by rejaverion** [mrnugget/opencv-haar-classifier-training#22]
Hi. When I try to execute mergevec.py the shell returns `TypeError: 'str' does not support the buffer interface"` for lines 170 and 120

Turns out there is a distinct incompatibilty between Py 2.x and 3.x that causes this error. How do I modify the py script to make it compatible with my Python 3.4?

**Comment by rejaverion** [comment]
I got the solution. Python 3,x treats unicode string and byte string differently. So you need to change 'str' data types to 'bytes'

**Comment by Timebutt** [comment]
Hi @rejaverion, I'm no Python expert: how exactly would one solve this issue then? I get the following error when trying to run the _mergevec.py_ script with Python 3.6 (on Windows x64):

```
Traceback (most recent call last):
  File "tools/mergevec.py", line 170, in <module>
    merge_vec_files(vec_directory, output_filename)
  File "tools/mergevec.py", line 120, in merge_vec_files
    val = struct.unpack('<iihh', content[:12])
TypeError: a bytes-like object is required, not 'str'
```

Are we having the same issue?
Changing the _str(_ to _bytes(_ on lines 119, 132 and 156 doesn't solve my issue.

It would be a great idea if this repository offered the mergevec.py both for Python 2.x and 3.x, that way nobody runs into this issue again.

**Comment by rrphotosoft** [comment]
Hi,
I'm facing the same issue, any idea on how to solve this? @rejaverion @Timebutt

**Comment by Timebutt** [comment]
Hi @rrphotosoft, if I recall correctly I just installed Python 2.7 and ran it with that Python version. There are plenty of other libraries that don't support Python 3 yet anyway, so I'd say it really is a necessity to have both version on your development machine ;)
