### ISSUE TITLE
Only empty vec files

### ISSUE THREAD

**Issue by luckk93** [mrnugget/opencv-haar-classifier-training#24]
Hello, I’m trying to follow your tutorial to create Haar cascade Training Files but at the step 5, it create 19 .vec files, but their are all empty (0 byte) so the step 6 fail.
I have 20 positive photos and 100 negative photos, all with 4160 x 2340 pixels, so my -w and -h are 128 and 72 (same ratio). All the steps have been done on a linux virtual machine.

I hope you can help my find the problem.

The command:

```
perl bin/createsamples.pl positives.txt negatives.txt samples 400  "opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1\
  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72"
```

The log:

```
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234350.jpg -bg tmp -vec samples/20161122_234350.jpg.vec -num 22
Info file name: (NULL)
Img file name: ./positive_images/20161122_234350.jpg
Vec file name: samples/20161122_234350.jpg.vec
BG  file name: tmp
Num: 22
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234654.jpg -bg tmp -vec samples/20161122_234654.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234654.jpg
Vec file name: samples/20161122_234654.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234418.jpg -bg tmp -vec samples/20161122_234418.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234418.jpg
Vec file name: samples/20161122_234418.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234423.jpg -bg tmp -vec samples/20161122_234423.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234423.jpg
Vec file name: samples/20161122_234423.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234305.jpg -bg tmp -vec samples/20161122_234305.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234305.jpg
Vec file name: samples/20161122_234305.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234313.jpg -bg tmp -vec samples/20161122_234313.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234313.jpg
Vec file name: samples/20161122_234313.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234432.jpg -bg tmp -vec samples/20161122_234432.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234432.jpg
Vec file name: samples/20161122_234432.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234219.jpg -bg tmp -vec samples/20161122_234219.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234219.jpg
Vec file name: samples/20161122_234219.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234244.jpg -bg tmp -vec samples/20161122_234244.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234244.jpg
Vec file name: samples/20161122_234244.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234024.jpg -bg tmp -vec samples/20161122_234024.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234024.jpg
Vec file name: samples/20161122_234024.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234659.jpg -bg tmp -vec samples/20161122_234659.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234659.jpg
Vec file name: samples/20161122_234659.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234255.jpg -bg tmp -vec samples/20161122_234255.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234255.jpg
Vec file name: samples/20161122_234255.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234335.jpg -bg tmp -vec samples/20161122_234335.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234335.jpg
Vec file name: samples/20161122_234335.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234633.jpg -bg tmp -vec samples/20161122_234633.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234633.jpg
Vec file name: samples/20161122_234633.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234339.jpg -bg tmp -vec samples/20161122_234339.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234339.jpg
Vec file name: samples/20161122_234339.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234012.jpg -bg tmp -vec samples/20161122_234012.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234012.jpg
Vec file name: samples/20161122_234012.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234021.jpg -bg tmp -vec samples/20161122_234021.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234021.jpg
Vec file name: samples/20161122_234021.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234456.jpg -bg tmp -vec samples/20161122_234456.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234456.jpg
Vec file name: samples/20161122_234456.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...
opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234035.jpg -bg tmp -vec samples/20161122_234035.jpg.vec -num 21
Info file name: (NULL)
Img file name: ./positive_images/20161122_234035.jpg
Vec file name: samples/20161122_234035.jpg.vec
BG  file name: tmp
Num: 21
BG color: 0
BG threshold: 0
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 128
Height: 72
Create training samples from single image applying distortions...

```

**Comment by mrnugget** [comment]
Which version of OpenCV are you using?

**Comment by luckk93** [comment]
Opencv 2.4.8

**Comment by mrnugget** [comment]
I'm sorry to say, I don't have any idea. This looks good to me. The only thing I can recommend is [reading through the remarks of the original author of opencv_createsamples.pl](http://note.sonots.com/SciSoftware/haartraining.html#e5c54f60)

**Comment by developer239** [comment]
Try setting right `chmod` to `samples` folder.

Also this one liner is easier to use: `perl bin/createsamples.pl positives.txt negatives.txt samples 1700 "opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1 -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 24 -h 24"`

**Comment by PratikshaDanti** [comment]
> Hello, I’m trying to follow your tutorial to create Haar cascade Training Files but at the step 5, it create 19 .vec files, but their are all empty (0 byte) so the step 6 fail.
> I have 20 positive photos and 100 negative photos, all with 4160 x 2340 pixels, so my -w and -h are 128 and 72 (same ratio). All the steps have been done on a linux virtual machine.
> 
> I hope you can help my find the problem.
> 
> The command:
> 
> ```
> perl bin/createsamples.pl positives.txt negatives.txt samples 400  "opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1\
>   -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72"
> ```
> 
> The log:
> 
> ```
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234350.jpg -bg tmp -vec samples/20161122_234350.jpg.vec -num 22
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234350.jpg
> Vec file name: samples/20161122_234350.jpg.vec
> BG  file name: tmp
> Num: 22
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234654.jpg -bg tmp -vec samples/20161122_234654.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234654.jpg
> Vec file name: samples/20161122_234654.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234418.jpg -bg tmp -vec samples/20161122_234418.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234418.jpg
> Vec file name: samples/20161122_234418.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234423.jpg -bg tmp -vec samples/20161122_234423.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234423.jpg
> Vec file name: samples/20161122_234423.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234305.jpg -bg tmp -vec samples/20161122_234305.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234305.jpg
> Vec file name: samples/20161122_234305.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234313.jpg -bg tmp -vec samples/20161122_234313.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234313.jpg
> Vec file name: samples/20161122_234313.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234432.jpg -bg tmp -vec samples/20161122_234432.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234432.jpg
> Vec file name: samples/20161122_234432.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234219.jpg -bg tmp -vec samples/20161122_234219.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234219.jpg
> Vec file name: samples/20161122_234219.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234244.jpg -bg tmp -vec samples/20161122_234244.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234244.jpg
> Vec file name: samples/20161122_234244.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234024.jpg -bg tmp -vec samples/20161122_234024.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234024.jpg
> Vec file name: samples/20161122_234024.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234659.jpg -bg tmp -vec samples/20161122_234659.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234659.jpg
> Vec file name: samples/20161122_234659.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234255.jpg -bg tmp -vec samples/20161122_234255.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234255.jpg
> Vec file name: samples/20161122_234255.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234335.jpg -bg tmp -vec samples/20161122_234335.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234335.jpg
> Vec file name: samples/20161122_234335.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234633.jpg -bg tmp -vec samples/20161122_234633.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234633.jpg
> Vec file name: samples/20161122_234633.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234339.jpg -bg tmp -vec samples/20161122_234339.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234339.jpg
> Vec file name: samples/20161122_234339.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234012.jpg -bg tmp -vec samples/20161122_234012.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234012.jpg
> Vec file name: samples/20161122_234012.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234021.jpg -bg tmp -vec samples/20161122_234021.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234021.jpg
> Vec file name: samples/20161122_234021.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234456.jpg -bg tmp -vec samples/20161122_234456.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234456.jpg
> Vec file name: samples/20161122_234456.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 128 -h 72 -img ./positive_images/20161122_234035.jpg -bg tmp -vec samples/20161122_234035.jpg.vec -num 21
> Info file name: (NULL)
> Img file name: ./positive_images/20161122_234035.jpg
> Vec file name: samples/20161122_234035.jpg.vec
> BG  file name: tmp
> Num: 21
> BG color: 0
> BG threshold: 0
> Invert: FALSE
> Max intensity deviation: 40
> Max x angle: 1.1
> Max y angle: 1.1
> Max z angle: 0.5
> Show samples: FALSE
> Width: 128
> Height: 72
> Create training samples from single image applying distortions...
> ```

were you able to solve this issue, if yes, please help me
