### ISSUE TITLE
opencv_traincascade  Error - classifier/params.xml can not be opened

### ISSUE THREAD

**Issue by eravion** [mrnugget/opencv-haar-classifier-training#26]
Hello,

After the opencv_traincascade command I have this error message :
Parameters can not be written, because file classifier/params.xml can not be opened.

I think that the folder have to be created by hand, no ?

[EDIT] I've got it.
I was not using your tool from the default folder.
Despite for mergevec which is creating "samples" folder, opencv_traincascade is not creating "classifier" folder.

**Comment by mrnugget** [comment]
Glad you found a solution :)

**Comment by rajarao47** [comment]
Hello,
I have uploaded 655 positive and 1975 negative pictures. I could generate and merge .vec file. 
While executing  below command;
_opencv_traincascade -data classifier -vec samples.vec -bg negatives.txt -numStages 20 -minHitRate 0.999 -maxFalseAlarmRate 0.5 -numPos 1976 -numNeg 655 -w 24 -h 24 -mode ALL -precalcValBufSize 1024 -precalcIdxBufSize 1024 -featureType LBP_
I am getting following error message:

OpenCV Error: Assertion failed (_img.rows * _img.cols == vecSize) in get, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/apps/traincascade/imagestorage.cpp, line 157
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/apps/traincascade/imagestorage.cpp:157: error: (-215) _img.rows * _img.cols == vecSize in function get

Aborted (core dumped)

I am using web server with 1Gb RAM and hope this is adequate enough to train the cascade.
I have installed opencv-2.4.9. 
Positive image size used is 50  by 50 
Negative image size is 100 by 100
![pepper_13](https://user-images.githubusercontent.com/29630319/28115405-66f85d0c-6737-11e7-9e16-0ad6707a8f10.jpg)
![neg_02](https://user-images.githubusercontent.com/29630319/28115418-7c45511a-6737-11e7-8d82-609d6bb7bf87.jpg)


Please help.


![train cascade error](https://user-images.githubusercontent.com/29630319/28113913-216fabe2-6731-11e7-96ed-8c4d2882a238.png)

**Comment by MilindKgp** [comment]
@rajarao47 
Try changing -w 50 -h 50 in your command.
I encountered a similar problem, changed them to image dimensions and it worked.

**Comment by jpmoraga** [comment]
> Hello,
> 
> After the opencv_traincascade command I have this error message :
> Parameters can not be written, because file classifier/params.xml can not be opened.
> 
> I think that the folder have to be created by hand, no ?
> 
> [EDIT] I've got it.
> I was not using your tool from the default folder.
> Despite for mergevec which is creating "samples" folder, opencv_traincascade is not creating "classifier" folder.

Where do you create the classifier folder? In the data folder?
