### ISSUE TITLE
Time for training takes too long 

### ISSUE THREAD

**Issue by hskang9** [mrnugget/opencv-haar-classifier-training#28]
I have to wait for 2~3 days to create a classifier. Is there any configuration for faster training?

**Comment by mrnugget** [comment]
Besides upgrading to a beefier computer? I don't think so, no.

**Comment by hskang9** [comment]
Faster training can be achieved with local binary pattern. 
See documentation on 
http://docs.opencv.org/2.4.13.2/doc/user_guide/ug_traincascade.html

**Comment by hskang9** [comment]
Training time shortened with -LBP option, so why not add that in README.md?

**Comment by hskang9** [comment]
Can you reopen this issue?

**Comment by hskang9** [comment]
Can I also recommend this option for people who cannot afford beefier computer? 😂
