### ISSUE TITLE
Training not happening

### ISSUE THREAD

**Issue by shashankvkt** [mrnugget/opencv-haar-classifier-training#31]
Hello,  
im getting the following error after executing the command to start training. 

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)

Could you please guide me. I have 80 samples of size 60x60 and have executed commands till acquiring the vector file successfully.

**Comment by mrnugget** [comment]
Sorry for only replying just now, but have you had any luck getting your training process started now?

**Comment by shashankvkt** [comment]
hello sir,
yes sir i was able to train my data set properly, apparently made some errors in the command line. Thanks to your repo.
cheers

**Comment by RubensZimbres** [comment]
I have a similar issue as @shashankvkt did. I run the opencv_createsamples but the command does not create the info.lst properly. This is generating an error in opencv_traincascade, as seen below:

opencv_createsamples -img anaconda3/pos/person1.jpg -bg bg.txt -info info/info.lst -pngoutput info -maxxangle 0.5 - maxyangle -0.5 -maxzangle 0.5 -num 6 -vec negatives.vec

Info file name: info/info.lst
Img file name: anaconda3/pos/Milla_JojoSmall1.jpg
Vec file name: negatives.vec
BG  file name: bg.txt
Num: 6
BG color: 0
BG threshold: 80
Invert: FALSE
Max intensity deviation: 40
Max x angle: 0.5
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 24
Height: 24
Max Scale: -1
Create training samples from single image applying distortions...
Done

**Then**

opencv_createsamples -info info/info.lst -num 6 -w 20 -h 20 -vec positives.vec

Info file name: info/info.lst
Img file name: (NULL)
Vec file name: positives.vec
BG  file name: (NULL)
Num: 6
BG color: 0
BG threshold: 80
Invert: FALSE
Max intensity deviation: 40
Max x angle: 1.1
Max y angle: 1.1
Max z angle: 0.5
Show samples: FALSE
Width: 20
Height: 20
Max Scale: -1
Create training samples from images collection...
Unable to open file: info/info.lst              **here**
Done. Created 0 samples

The effect is a failure in opencv_traincascade:

opencv_traincascade -data data -vec positives.vec -bg bg.txt -numPos 6 -numNeg 6 - numStages 5 -w 20 -h 20 -precalcValBufSize 1024 -minHitRate 0.999 -maxFalseAlarmRate 0.5 -mode ALL

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted

All samples are 50x50

What can i do ?

Thanks in advance

**Comment by ryanpram** [comment]
@shashankvkt how you fix your problem? i get same problem.. pls help me

**Comment by shashankvkt** [comment]
Hey @ryanpram Try writing the command on the terminal in the same line and give the path to your positive and negative samples correctly. It should work.
Apologies for the late reply

**Comment by Devanshice020** [comment]
@shashankvkt 
I am getting the same issue can you please help me it's urgent.
Thanks in advance

**Comment by RubensZimbres** [comment]
@Devanshice020 I did a summary of the commands of haar cascade training in my repo:

https://github.com/RubensZimbres/Repo-2018/blob/master/OpenCV/Haarcascade_Training.pdf
