### ISSUE TITLE
Where is ./facedetect file location?

### ISSUE THREAD

**Issue by herleeyandi** [mrnugget/opencv-haar-classifier-training#32]
I have successfully run and train the classifier, but to save into the file I have a problem.
1) Where I can find `./build_all.sh` file if I am using ubuntu?
2) I manage by cloning to the repository, but the problem is I can not get file `./facedetect` so where is the file location?, I just find `facedetect.cmd` and I use but not run. How can I find this file in case I have installed openCV before?
3) In case I failed to save the file to .xml, is it possible to do it later I mean like our trained data is save before writing the file .xml?
Here is the error message `bash: ./facedetect: No such file or directory`

**Comment by mrnugget** [comment]
The `facedetect` mentioned in the README comes from [the original blogpost, this repository is a companion to](http://coding-robin.de/2013/07/22/train-your-own-opencv-haar-classifier.html).
