### ISSUE TITLE
"std::bad_alloc" error

### ISSUE THREAD

**Issue by shubhkr** [mrnugget/opencv-haar-classifier-training#33]
when I run the command to train classifier i get the following error:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Same exact thing works on my vmware (ubuntu 14.04) but I wanted to run it on amazon EC2 instance as it was taking too much time on my pc (ubuntu 16.04 there). But there I get this error.. What is the problem?

**Comment by mrnugget** [comment]
I guess the difference might be some dynamic libraries the process is using, since those might differ from system to system. I guess it's up to you now to find the difference in your setups, since the process is working on one system but not on the other.

**Comment by shubhkr** [comment]
Yeah the problem was the EC2 instance where i was running this had very low ram (as it was a micro instance). So, heap memory was getting full hence, bad_alloc error. When i switched to a medium instance the error was no longer there..

**Comment by mrnugget** [comment]
Thanks for the update! :)
