### ISSUE TITLE
Local binary pattern for faster haar training yet with almost the same quality

### ISSUE THREAD

**Issue by hskang9** [mrnugget/opencv-haar-classifier-training#36]
As mentioned in #28 , I, macbook pro user, tried to make the training work with ease.

**Comment by hskang9** [comment]
#28

**Comment by mrnugget** [comment]
Hey, thanks for investigating this and finding a solution! How about opening a pull request and adding the option to the README?

**Comment by hskang9** [comment]
With pleasure.

**Comment by mrnugget** [comment]
Closing this, as the PR is merged!
