### ISSUE TITLE
str.unpack error

### ISSUE THREAD

**Issue by rrphotosoft** [mrnugget/opencv-haar-classifier-training#39]
Hi,

I have gotten to the step where, i need to combine the individual vector files, into a single vector file using the mergevec.py program.
I get an error at line 121 of the program:
```
val = struct.unpack('<iihh', content[:12])
```
The error is:
```
TypeError: a bytes-like object is required, not 'str'
```
My python version is: 3.6.0
Please can you help?

**Comment by Peter-B-** [comment]
Hello,

I encountered the same problem. I'm new to python, but I belive that the file is read as a string and not as a byte array.

For me it worked after I replaced all three
`content = ''.join(str(line) for line in vecfile.readlines())`
with
`content = vecfile.read()`

**Comment by fatalfeel** [comment]
very good

**Comment by sebaxtian** [comment]
Thank you @Peter-B- 
I replaced each line in the code with the new python 3 version and it worked for me too.
