### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pradeepktg** [mrnugget/opencv-haar-classifier-training#4]
Hi , I'm using mac. I get error when i execute this statement in terminal
perl bin/createsamples.pl positives.txt negatives.txt samples 1700 
"opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1
-maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 24 -h 24"
Error is : sh: -c: line 0: syntax error near unexpected token `(' .
What could be the issue ?

**Comment by sunaina123** [comment]
please help me to solve my error....... I have run the createsamples command but my info folder is empty.
