### ISSUE TITLE
TypeError when execute python ./tools/mergevec.py -v samples/ -o samples.vec

### ISSUE THREAD

**Issue by fourk-ty** [mrnugget/opencv-haar-classifier-training#42]
When I execute this command "python ./tools/mergevec.py -v samples/ -o samples.vec"  in my computer, I met a problem: TypeError: a bytes-like object is required, not 'str'. Could someone tell me what should I do?

**Comment by thielsn** [comment]
There is a python 3 version that is actually working in:
https://github.com/wulfebw/mergevec/blob/master/mergevec.py
