### ISSUE TITLE
Can anyone help me out with foll error?

### ISSUE THREAD

**Issue by ameyakale603** [mrnugget/opencv-haar-classifier-training#43]
===== TRAINING 0-stage =====
<BEGIN
OpenCV Error: Bad argument (Can not get new positive sample. The most possible reason is insufficient count of samples in given vec-file.
) in get, file /opt/conda/conda-bld/opencv_1491943970124/work/opencv-3.1.0/apps/traincascade/imagestorage.cpp, line 157
terminate called after throwing an instance of 'cv::Exception'
  what():  /opt/conda/conda-bld/opencv_1491943970124/work/opencv-3.1.0/apps/traincascade/imagestorage.cpp:157: error: (-5) Can not get new positive sample. The most possible reason is insufficient count of samples in given vec-file.
 in function get

Aborted (core dumped)

**Comment by saideepthik** [comment]
hi,
positive images vector samples should be less than the number which you gave while creating vector samples.
like this....
perl bin/createsamples.pl positives.txt negatives.txt samples 1500\
   "opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1\
   -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 80 -h 40"
lets this....

**Comment by bharathkotari** [comment]
yes , the above solution worked for me . @saideepthik

**Comment by mrnugget** [comment]
Thanks for the comment and feedback @saideepthik and @bharathkotari -- I'll close this for now.
