### ISSUE TITLE
Illegal division by zero at bin/createsamples.pl line 45.

### ISSUE THREAD

**Issue by qkmaosjtu** [mrnugget/opencv-haar-classifier-training#46]
![image](https://user-images.githubusercontent.com/16631352/34552569-29ce69b6-f15d-11e7-822b-56941750c99a.png)

**Comment by saideepthik** [comment]
hi,
this issue get resolved by giving more positive and negative samples (num>100 is good).
i too got same issue then i increased the samples.

**Comment by michaelvogt** [comment]
I just had the same error. Looks like the first line in positives.txt is ignored. Since I only have one positive file, the resulting number of items was zero. Hence the exception.

I solved it by duplicating the line in positives.txt. Exception gone, createsamples.pl ran through the end.

**Comment by arvindiyer1994** [comment]
Make sure the images for in .jpg format else change the command to input png and jpeg files(I had to do that)
