### ISSUE TITLE
Missed cvsampleoutput.cpp in step six

### ISSUE THREAD

**Issue by lethic** [mrnugget/opencv-haar-classifier-training#5]
It should be
```
g++ `pkg-config --libs --cflags opencv` -I. -o mergevec mergevec.cpp  cvboost.cpp cvcommon.cpp cvsamples.cpp cvhaarclassifier.cpp  cvhaartraining.cpp  cvsamplesoutput.cpp -lopencv_core -lopencv_calib3d -lopencv_imgproc -lopencv_highgui -lopencv_objdetect
```

**Comment by mrnugget** [comment]
Are you sure? Last time I checked I didn't need the `cvsampleoutput.cpp`. Does it fail to compile for you? Which version?

**Comment by lethic** [comment]
Yes, it might be a version problem. My version is opencv-2.4.10. But someone on [stackoverflow](http://stackoverflow.com/questions/27481644/c-compile-error-when-i-try-to-learn-opencv-train-features)  using 2.4.9 also got the same problem:
```
undefined reference to `IOutput::createOutput(char const*, IOutput::OutputType)'
```

**Comment by mrnugget** [comment]
I can't reproduce this with opencv-2.4.9. I just ran the commands from scratch described in the README:
```
$ cd opencv-2.4.9
/opencv-2.4.9 $ cd apps/haartraining
/opencv-2.4.9/apps/haartraining $ cp ~/code/projects/opencv-haar-classifier-training/src/mergevec.cpp .
/opencv-2.4.9/apps/haartraining $ g++ `pkg-config --libs --cflags opencv | sed 's/libtbb\.dylib/tbb/'` -I. -o mergevec mergevec.cpp cvboost.cpp cvcommon.cpp cvsamples.cpp cvhaarclassifier.cpp cvhaartraining.cpp -lopencv_core -lopencv_calib3d -lopencv_imgproc -lopencv_highgui -lopencv_objdetect
/opencv-2.4.9/apps/haartraining $ ls -la ./mergevec
-rwxr-xr-x  1 mrnugget  staff  306596 Jan 24 15:35 ./mergevec
```

Please note: the steps described in the README are based on my experiences running it on OS X.

**Comment by lethic** [comment]
I was using Ubuntu 14.04. I don't know why it behaves differently in different operation system. 
Anyway, thank you for your replication and your instruction which did help me a lot.

**Comment by mrnugget** [comment]
I think there are several reasons why it might behave differently:
* different compiler
* different header files
* different `ifdef`s in the header files
* different pkg-config configuration

That's why building complex projects without a proper build tool is such a hassle and why I'm hesitant about recommending to use this tutorial on anything other than OS X.

If someone wants to do the work and update the instructions for Linux, I'd happily merge this :)
