### ISSUE TITLE
how createsamples.pl will works?

### ISSUE THREAD

**Issue by saideepthik** [mrnugget/opencv-haar-classifier-training#51]
i need to know that how this perl scripting making vector files taking +ves over -ve bankground images? as a aspirant i want know this concepts with in depth details if any one could find any information on this haar cascade classifier please us know.
share with us our team aspirants were always waiting for any details.
thanks in advance.

**Comment by mrnugget** [comment]
As mentioned in the [References & Links](https://github.com/mrnugget/opencv-haar-classifier-training#references--links), there is Naotoshi Seo's site, the creator of `createsamples.pl`: http://note.sonots.com/SciSoftware/haartraining.html#w0a08ab4
