### ISSUE TITLE
Error when create samples

### ISSUE THREAD

**Issue by kongpon1995** [mrnugget/opencv-haar-classifier-training#52]
I have follow all your steps, but finally the issues happen. I need all your help thanks.
<img width="1440" alt="screen shot 2561-04-23 at 18 13 15" src="https://user-images.githubusercontent.com/30767772/39123564-6b1c9472-4722-11e8-85e8-90a0c98070df.png">

**Comment by arizalzr** [comment]
how you fix that problem ?
