### ISSUE TITLE
opencv_traincascade assertion error

### ISSUE THREAD

**Issue by BartMitTyp** [mrnugget/opencv-haar-classifier-training#61]
The vec file is merged now, but when I execute 

```opencv_traincascade -data classifier -vec samples.vec -bg negatives.txt -numStages 20 -minHitRate 0.999 -maxFalseAlarmRate 0.5 -numPos 1000 -numNeg 600 -w 80 -h 40 -mode ALL -precalcValBufSize 1024 -precalcIdxBufSize 1024```

it says 

```OpenCV Error: Assertion failed (_img.rows * _img.cols == vecSize) in CvCascadeImageReader::PosReader::get, file C:\builds\2_4_PackSlave-win64-vc12-shared\opencv\apps\traincascade\imagestorage.cpp, line 157```

I can't seem to resolve the problem. I use opencv version 2.4.9 as stated in the tutorial, python 3.6 (but had to use 2.7 to execute mergevec)
Can anyone help me?

**Comment by elifozcakir** [comment]
The width and height values ​​you entered in the previous command don't match the values ​​in this command. 
**perl bin/createsamples.pl positives.txt negatives.txt samples 1500\
   "opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1\
   -maxyangle 1.1 maxzangle 0.5 -maxidev 40  -w 80 -h 40"**

**opencv_traincascade -data classifier -vec samples.vec -bg negatives.txt\
   -numStages 20 -minHitRate 0.999 -maxFalseAlarmRate 0.5 -numPos 1000\
   -numNeg 600 -w 80 -h 40 -mode ALL -precalcValBufSize 1024\
   -precalcIdxBufSize 1024**

Checking whether -w and -h are the same in both commands and running the command again may solve the problem.

**Comment by BartMitTyp** [comment]
Oh sorry, I already forgot about this issue. My mistake was that my training data was quadratic with 40x40, but thank you anyways :)
