### ISSUE TITLE
Needed to include cvsamplesoutput.cpp in step 6

### ISSUE THREAD

**Issue by superlou** [mrnugget/opencv-haar-classifier-training#7]
I was initially receiving `cvhaartraining.cpp:(.text+0xafd5): undefined reference to 'IOutput::createOutput(char const*, IOutput::OutputType)'` during step 6.  In order to compile mergevec, I needed to use the following command:

g++ `pkg-config --libs --cflags opencv | sed 's/libtbb\.dylib/tbb/'`  -I. -o mergevec mergevec.cpp  cvboost.cpp cvcommon.cpp cvsamples.cpp cvhaarclassifier.cpp  cvhaartraining.cpp cvsamplesoutput.cpp  -lopencv_core -lopencv_calib3d -lopencv_imgproc -lopencv_highgui -lopencv_objdetect

I think someone else ran into this issue on [Stackoverflow](http://stackoverflow.com/questions/27481644/c-compile-error-when-i-try-to-learn-opencv-train-features) as well.

**Comment by mrnugget** [comment]
(Sorry for the late reply, I was on holiday)

The steps in the tutorial still work for me on my machine. Which setup are you using? OS X? Linux? Which version of OpenCV?

If you can find out which difference in the system setup causes this error message, you could open a Pull Request that adds the information to the README of this repo. Maybe with a note that says: "If you try to run this with X on Y and run into Z, use this: [...]".

**Comment by superlou** [comment]
No problem.  I'm on Linux (Mint 17) with opencv-2.4.11 compiled locally.  If I can pin down the difference, I'll submit a PR.

**Comment by mrnugget** [comment]
ah, that's it! I didn't write the tutorial with Linux in mind. Which does not mean that it's not possible to use with Linux, but I just didn't get around to test it on Linux.

If someone would provide instructions for Linux (replace `brew` with something else and so on) I'd merge it.

**Comment by romulogcerqueira** [comment]
Initially I had the same problem. I include "cvsamplesoutput.cpp" and Voilà! ;)

**Comment by mrnugget** [comment]
I'm closing this for now. If someone wants to provide instructions for Linux a pull request would be greatly appreciated :)

**Comment by superlou** [comment]
@mrnugget, hopefully will be able to look into it once it's cool enough to run my computer long enough to train the classifiers.  I'm afraid to put one together until I know if I have it working right, and so far haven't had much luck with my classifier.
